---
abstract: "access to mtgox.com's bitcoin trading API"
author:
  - 'John BEPPU <beppu {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-MtGox
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moo: 0
  Ouch: 0
  parent: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/beppu/webservice-mtgox.git
version: 0.04
